import massive.munit.TestSuite;
import openfl.AssetsTest;
import openfl.desktop.ClipboardFormatsTest;
import openfl.desktop.ClipboardTest;
import openfl.desktop.ClipboardTransferModeTest;
import openfl.display.ApplicationTest;
import openfl.display.AVM1MovieTest;
import openfl.display.BitmapDataChannelTest;
import openfl.display.BitmapDataTest;
import openfl.display.BitmapTest;
import openfl.display.BlendModeTest;
import openfl.display.CapsStyleTest;
import openfl.display.DisplayObjectContainerTest;
import openfl.display.DisplayObjectTest;
import openfl.display.DOMElementTest;
import openfl.display.FPSTest;
import openfl.display.FrameLabelTest;
import openfl.display.GradientTypeTest;
import openfl.display.GraphicsBitmapFillTest;
import openfl.display.GraphicsEndFillTest;
import openfl.display.GraphicsGradientFillTest;
import openfl.display.GraphicsPathCommandTest;
import openfl.display.GraphicsPathTest;
import openfl.display.GraphicsPathWindingTest;
import openfl.display.GraphicsSolidFillTest;
import openfl.display.GraphicsStrokeTest;
import openfl.display.GraphicsTest;
import openfl.display.InteractiveObjectTest;
import openfl.display.InterpolationMethodTest;
import openfl.display.JointStyleTest;
import openfl.display.JPEGEncoderOptionsTest;
import openfl.display.LineScaleModeTest;
import openfl.display.LoaderInfoTest;
import openfl.display.LoaderTest;
import openfl.display.MovieClipTest;
import openfl.display.PixelSnappingTest;
import openfl.display.PNGEncoderOptionsTest;
import openfl.display.PreloaderTest;
import openfl.display.ShaderDataTest;
import openfl.display.ShaderInputTest;
import openfl.display.ShaderJobTest;
import openfl.display.ShaderParameterTest;
import openfl.display.ShaderParameterTypeTest;
import openfl.display.ShaderPrecisionTest;
import openfl.display.ShaderTest;
import openfl.display.ShapeTest;
import openfl.display.SimpleButtonTest;
import openfl.display.SpreadMethodTest;
import openfl.display.SpriteTest;
import openfl.display.Stage3DTest;
import openfl.display.StageAlignTest;
import openfl.display.StageDisplayStateTest;
import openfl.display.StageQualityTest;
import openfl.display.StageScaleModeTest;
import openfl.display.StageTest;
import openfl.display.TilemapTest;
import openfl.display.TilesetTest;
import openfl.display.TileTest;
import openfl.display.TriangleCullingTest;
import openfl.display.WindowTest;
import openfl.display3D.Context3DBlendFactorTest;
import openfl.display3D.Context3DBufferUsageTest;
import openfl.display3D.Context3DClearMaskTest;
import openfl.display3D.Context3DCompareModeTest;
import openfl.display3D.Context3DMipFilterTest;
import openfl.display3D.Context3DProfileTest;
import openfl.display3D.Context3DProgramTypeTest;
import openfl.display3D.Context3DRenderModeTest;
import openfl.display3D.Context3DStencilActionTest;
import openfl.display3D.Context3DTest;
import openfl.display3D.Context3DTextureFilterTest;
import openfl.display3D.Context3DTextureFormatTest;
import openfl.display3D.Context3DTriangleFaceTest;
import openfl.display3D.Context3DVertexBufferFormatTest;
import openfl.display3D.Context3DWrapModeTest;
import openfl.display3D.IndexBuffer3DTest;
import openfl.display3D.Program3DTest;
import openfl.display3D.textures.CubeTextureTest;
import openfl.display3D.textures.RectangleTextureTest;
import openfl.display3D.textures.TextureBaseTest;
import openfl.display3D.textures.TextureTest;
import openfl.display3D.VertexBuffer3DTest;
import openfl.errors.ArgumentErrorTest;
import openfl.errors.EOFErrorTest;
import openfl.errors.ErrorTest;
import openfl.errors.IllegalOperationErrorTest;
import openfl.errors.IOErrorTest;
import openfl.errors.RangeErrorTest;
import openfl.errors.SecurityErrorTest;
import openfl.errors.TypeErrorTest;
import openfl.events.AccelerometerEventTest;
import openfl.events.ActivityEventTest;
import openfl.events.AsyncErrorEventTest;
import openfl.events.DataEventTest;
import openfl.events.ErrorEventTest;
import openfl.events.EventDispatcherTest;
import openfl.events.EventPhaseTest;
import openfl.events.EventTest;
import openfl.events.FocusEventTest;
import openfl.events.FullScreenEventTest;
import openfl.events.GameInputEventTest;
import openfl.events.HTTPStatusEventTest;
import openfl.events.IOErrorEventTest;
import openfl.events.KeyboardEventTest;
import openfl.events.MouseEventTest;
import openfl.events.NetStatusEventTest;
import openfl.events.ProgressEventTest;
import openfl.events.SampleDataEventTest;
import openfl.events.SecurityErrorEventTest;
import openfl.events.TextEventTest;
import openfl.events.TimerEventTest;
import openfl.events.TouchEventTest;
import openfl.events.UncaughtErrorEventsTest;
import openfl.events.UncaughtErrorEventTest;
import openfl.external.ExternalInterfaceTest;
import openfl.filters.BitmapFilterTest;
import openfl.filters.BitmapFilterTypeTest;
import openfl.filters.BlurFilterTest;
import openfl.filters.ColorMatrixFilterTest;
import openfl.filters.DropShadowFilterTest;
import openfl.filters.GlowFilterTest;
import openfl.filters.ShaderFilterTest;
import openfl.geom.ColorTransformTest;
import openfl.geom.Matrix3DTest;
import openfl.geom.MatrixTest;
import openfl.geom.Orientation3DTest;
import openfl.geom.PerspectiveProjectionTest;
import openfl.geom.PointTest;
import openfl.geom.RectangleTest;
import openfl.geom.TransformTest;
import openfl.geom.Utils3DTest;
import openfl.geom.Vector3DTest;
import openfl.LibTest;
import openfl.media.ID3InfoTest;
import openfl.media.SoundChannelTest;
import openfl.media.SoundLoaderContextTest;
import openfl.media.SoundTest;
import openfl.media.SoundTransformTest;
import openfl.MemoryTest;
import openfl.net.SharedObjectFlushStatusTest;
import openfl.net.SharedObjectTest;
import openfl.net.URLLoaderDataFormatTest;
import openfl.net.URLLoaderTest;
import openfl.net.URLRequestHeaderTest;
import openfl.net.URLRequestMethodTest;
import openfl.net.URLRequestTest;
import openfl.net.URLVariablesTest;
import openfl.sensors.AccelerometerTest;
import openfl.system.ApplicationDomainTest;
import openfl.system.CapabilitiesTest;
import openfl.system.LoaderContextTest;
import openfl.system.SecurityDomainTest;
import openfl.system.SystemTest;
import openfl.text.AntiAliasTypeTest;
import openfl.text.FontStyleTest;
import openfl.text.FontTest;
import openfl.text.FontTypeTest;
import openfl.text.GridFitTypeTest;
import openfl.text.TextFieldAutoSizeTest;
import openfl.text.TextFieldTest;
import openfl.text.TextFieldTypeTest;
import openfl.text.TextFormatAlignTest;
import openfl.text.TextFormatTest;
import openfl.text.TextLineMetricsTest;
import openfl.ui.KeyboardTest;
import openfl.ui.MouseTest;
import openfl.ui.MultitouchInputModeTest;
import openfl.ui.MultitouchTest;
import openfl.utils.ByteArrayTest;
import openfl.utils.CompressionAlgorithmTest;
import openfl.utils.DictionaryTest;
import openfl.utils.EndianTest;
import openfl.utils.TimerTest;
import openfl.VectorTest;

/**
 * Auto generated Test Suite for MassiveUnit.
 * Refer to munit command line tool for more information (haxelib run munit)
 */
class UnitTestSuite extends massive.munit.TestSuite
{
	public function new()
	{
		super();

		add(openfl.AssetsTest);
		add(openfl.desktop.ClipboardFormatsTest);
		add(openfl.desktop.ClipboardTest);
		add(openfl.desktop.ClipboardTransferModeTest);
		add(openfl.display.ApplicationTest);
		add(openfl.display.AVM1MovieTest);
		add(openfl.display.BitmapDataChannelTest);
		add(openfl.display.BitmapDataTest);
		add(openfl.display.BitmapTest);
		add(openfl.display.BlendModeTest);
		add(openfl.display.CapsStyleTest);
		add(openfl.display.DisplayObjectContainerTest);
		add(openfl.display.DisplayObjectTest);
		add(openfl.display.DOMElementTest);
		add(openfl.display.FPSTest);
		add(openfl.display.FrameLabelTest);
		add(openfl.display.GradientTypeTest);
		add(openfl.display.GraphicsBitmapFillTest);
		add(openfl.display.GraphicsEndFillTest);
		add(openfl.display.GraphicsGradientFillTest);
		add(openfl.display.GraphicsPathCommandTest);
		add(openfl.display.GraphicsPathTest);
		add(openfl.display.GraphicsPathWindingTest);
		add(openfl.display.GraphicsSolidFillTest);
		add(openfl.display.GraphicsStrokeTest);
		add(openfl.display.GraphicsTest);
		add(openfl.display.InteractiveObjectTest);
		add(openfl.display.InterpolationMethodTest);
		add(openfl.display.JointStyleTest);
		add(openfl.display.JPEGEncoderOptionsTest);
		add(openfl.display.LineScaleModeTest);
		add(openfl.display.LoaderInfoTest);
		add(openfl.display.LoaderTest);
		add(openfl.display.MovieClipTest);
		add(openfl.display.PixelSnappingTest);
		add(openfl.display.PNGEncoderOptionsTest);
		add(openfl.display.PreloaderTest);
		add(openfl.display.ShaderDataTest);
		add(openfl.display.ShaderInputTest);
		add(openfl.display.ShaderJobTest);
		add(openfl.display.ShaderParameterTest);
		add(openfl.display.ShaderParameterTypeTest);
		add(openfl.display.ShaderPrecisionTest);
		add(openfl.display.ShaderTest);
		add(openfl.display.ShapeTest);
		add(openfl.display.SimpleButtonTest);
		add(openfl.display.SpreadMethodTest);
		add(openfl.display.SpriteTest);
		add(openfl.display.Stage3DTest);
		add(openfl.display.StageAlignTest);
		add(openfl.display.StageDisplayStateTest);
		add(openfl.display.StageQualityTest);
		add(openfl.display.StageScaleModeTest);
		add(openfl.display.StageTest);
		add(openfl.display.TilemapTest);
		add(openfl.display.TilesetTest);
		add(openfl.display.TileTest);
		add(openfl.display.TriangleCullingTest);
		add(openfl.display.WindowTest);
		add(openfl.display3D.Context3DBlendFactorTest);
		add(openfl.display3D.Context3DBufferUsageTest);
		add(openfl.display3D.Context3DClearMaskTest);
		add(openfl.display3D.Context3DCompareModeTest);
		add(openfl.display3D.Context3DMipFilterTest);
		add(openfl.display3D.Context3DProfileTest);
		add(openfl.display3D.Context3DProgramTypeTest);
		add(openfl.display3D.Context3DRenderModeTest);
		add(openfl.display3D.Context3DStencilActionTest);
		add(openfl.display3D.Context3DTest);
		add(openfl.display3D.Context3DTextureFilterTest);
		add(openfl.display3D.Context3DTextureFormatTest);
		add(openfl.display3D.Context3DTriangleFaceTest);
		add(openfl.display3D.Context3DVertexBufferFormatTest);
		add(openfl.display3D.Context3DWrapModeTest);
		add(openfl.display3D.IndexBuffer3DTest);
		add(openfl.display3D.Program3DTest);
		add(openfl.display3D.textures.CubeTextureTest);
		add(openfl.display3D.textures.RectangleTextureTest);
		add(openfl.display3D.textures.TextureBaseTest);
		add(openfl.display3D.textures.TextureTest);
		add(openfl.display3D.VertexBuffer3DTest);
		add(openfl.errors.ArgumentErrorTest);
		add(openfl.errors.EOFErrorTest);
		add(openfl.errors.ErrorTest);
		add(openfl.errors.IllegalOperationErrorTest);
		add(openfl.errors.IOErrorTest);
		add(openfl.errors.RangeErrorTest);
		add(openfl.errors.SecurityErrorTest);
		add(openfl.errors.TypeErrorTest);
		add(openfl.events.AccelerometerEventTest);
		add(openfl.events.ActivityEventTest);
		add(openfl.events.AsyncErrorEventTest);
		add(openfl.events.DataEventTest);
		add(openfl.events.ErrorEventTest);
		add(openfl.events.EventDispatcherTest);
		add(openfl.events.EventPhaseTest);
		add(openfl.events.EventTest);
		add(openfl.events.FocusEventTest);
		add(openfl.events.FullScreenEventTest);
		add(openfl.events.GameInputEventTest);
		add(openfl.events.HTTPStatusEventTest);
		add(openfl.events.IOErrorEventTest);
		add(openfl.events.KeyboardEventTest);
		add(openfl.events.MouseEventTest);
		add(openfl.events.NetStatusEventTest);
		add(openfl.events.ProgressEventTest);
		add(openfl.events.SampleDataEventTest);
		add(openfl.events.SecurityErrorEventTest);
		add(openfl.events.TextEventTest);
		add(openfl.events.TimerEventTest);
		add(openfl.events.TouchEventTest);
		add(openfl.events.UncaughtErrorEventsTest);
		add(openfl.events.UncaughtErrorEventTest);
		add(openfl.external.ExternalInterfaceTest);
		add(openfl.filters.BitmapFilterTest);
		add(openfl.filters.BitmapFilterTypeTest);
		add(openfl.filters.BlurFilterTest);
		add(openfl.filters.ColorMatrixFilterTest);
		add(openfl.filters.DropShadowFilterTest);
		add(openfl.filters.GlowFilterTest);
		add(openfl.filters.ShaderFilterTest);
		add(openfl.geom.ColorTransformTest);
		add(openfl.geom.Matrix3DTest);
		add(openfl.geom.MatrixTest);
		add(openfl.geom.Orientation3DTest);
		add(openfl.geom.PerspectiveProjectionTest);
		add(openfl.geom.PointTest);
		add(openfl.geom.RectangleTest);
		add(openfl.geom.TransformTest);
		add(openfl.geom.Utils3DTest);
		add(openfl.geom.Vector3DTest);
		add(openfl.LibTest);
		add(openfl.media.ID3InfoTest);
		add(openfl.media.SoundChannelTest);
		add(openfl.media.SoundLoaderContextTest);
		add(openfl.media.SoundTest);
		add(openfl.media.SoundTransformTest);
		add(openfl.MemoryTest);
		add(openfl.net.SharedObjectFlushStatusTest);
		add(openfl.net.SharedObjectTest);
		add(openfl.net.URLLoaderDataFormatTest);
		add(openfl.net.URLLoaderTest);
		add(openfl.net.URLRequestHeaderTest);
		add(openfl.net.URLRequestMethodTest);
		add(openfl.net.URLRequestTest);
		add(openfl.net.URLVariablesTest);
		add(openfl.sensors.AccelerometerTest);
		add(openfl.system.ApplicationDomainTest);
		add(openfl.system.CapabilitiesTest);
		add(openfl.system.LoaderContextTest);
		add(openfl.system.SecurityDomainTest);
		add(openfl.system.SystemTest);
		add(openfl.text.AntiAliasTypeTest);
		add(openfl.text.FontStyleTest);
		add(openfl.text.FontTest);
		add(openfl.text.FontTypeTest);
		add(openfl.text.GridFitTypeTest);
		add(openfl.text.TextFieldAutoSizeTest);
		add(openfl.text.TextFieldTest);
		add(openfl.text.TextFieldTypeTest);
		add(openfl.text.TextFormatAlignTest);
		add(openfl.text.TextFormatTest);
		add(openfl.text.TextLineMetricsTest);
		add(openfl.ui.KeyboardTest);
		add(openfl.ui.MouseTest);
		add(openfl.ui.MultitouchInputModeTest);
		add(openfl.ui.MultitouchTest);
		add(openfl.utils.ByteArrayTest);
		add(openfl.utils.CompressionAlgorithmTest);
		add(openfl.utils.DictionaryTest);
		add(openfl.utils.EndianTest);
		add(openfl.utils.TimerTest);
		add(openfl.VectorTest);
	}
}
