import massive.munit.TestSuite;

import openfl.desktop.ClipboardFormatsTest;
import openfl.desktop.ClipboardTest;
import openfl.desktop.ClipboardTransferModeTest;
import openfl.display.BitmapDataChannelTest;
import openfl.display.BlendModeTest;
import openfl.display.CapsStyleTest;
import openfl.display.GradientTypeTest;
import openfl.display.GraphicsEndFillTest;
import openfl.display.GraphicsGradientFillTest;
import openfl.display.GraphicsPathCommandTest;
import openfl.display.GraphicsPathTest;
import openfl.display.GraphicsPathWindingTest;
import openfl.display.GraphicsSolidFillTest;
import openfl.display.GraphicsStrokeTest;
import openfl.display.InterpolationMethodTest;
import openfl.display.JointStyleTest;
import openfl.display.JPEGEncoderOptionsTest;
import openfl.display.LineScaleModeTest;
import openfl.display.PixelSnappingTest;
import openfl.display.PNGEncoderOptionsTest;
import openfl.display.ShaderParameterTypeTest;
import openfl.display.ShaderPrecisionTest;
import openfl.display.SpreadMethodTest;
import openfl.display.StageAlignTest;
import openfl.display.StageDisplayStateTest;
import openfl.display.StageQualityTest;
import openfl.display.StageScaleModeTest;
import openfl.display.TriangleCullingTest;
import openfl.display3D.Context3DBlendFactorTest;
import openfl.display3D.Context3DBufferUsageTest;
import openfl.display3D.Context3DClearMaskTest;
import openfl.display3D.Context3DCompareModeTest;
import openfl.display3D.Context3DMipFilterTest;
import openfl.display3D.Context3DProfileTest;
import openfl.display3D.Context3DProgramTypeTest;
import openfl.display3D.Context3DRenderModeTest;
import openfl.display3D.Context3DStencilActionTest;
import openfl.display3D.Context3DTextureFilterTest;
import openfl.display3D.Context3DTextureFormatTest;
import openfl.display3D.Context3DTriangleFaceTest;
import openfl.display3D.Context3DVertexBufferFormatTest;
import openfl.display3D.Context3DWrapModeTest;
import openfl.errors.ArgumentErrorTest;
import openfl.errors.EOFErrorTest;
import openfl.errors.ErrorTest;
import openfl.errors.IllegalOperationErrorTest;
import openfl.errors.IOErrorTest;
import openfl.errors.RangeErrorTest;
import openfl.errors.SecurityErrorTest;
import openfl.errors.TypeErrorTest;
import openfl.external.ExternalInterfaceTest;
import openfl.filters.BitmapFilterTypeTest;
import openfl.geom.ColorTransformTest;
import openfl.geom.Matrix3DTest;
import openfl.geom.MatrixTest;
import openfl.geom.Orientation3DTest;
import openfl.geom.PointTest;
import openfl.geom.RectangleTest;
import openfl.geom.Utils3DTest;
import openfl.geom.Vector3DTest;
import openfl.LibTest;
import openfl.media.SoundChannelTest;
import openfl.media.SoundLoaderContextTest;
import openfl.media.SoundTransformTest;
import openfl.MemoryTest;
import openfl.net.SharedObjectFlushStatusTest;
import openfl.net.URLLoaderDataFormatTest;
import openfl.net.URLRequestHeaderTest;
import openfl.net.URLRequestMethodTest;
import openfl.net.URLRequestTest;
import openfl.net.URLVariablesTest;
import openfl.system.ApplicationDomainTest;
import openfl.system.CapabilitiesTest;
import openfl.system.LoaderContextTest;
import openfl.system.SecurityDomainTest;
import openfl.system.SystemTest;
import openfl.text.AntiAliasTypeTest;
import openfl.text.FontStyleTest;
import openfl.text.FontTypeTest;
import openfl.text.GridFitTypeTest;
import openfl.text.TextFieldAutoSizeTest;
import openfl.text.TextFieldTypeTest;
import openfl.text.TextFormatAlignTest;
import openfl.text.TextFormatTest;
import openfl.text.TextLineMetricsTest;
import openfl.ui.KeyboardTest;
import openfl.ui.MouseTest;
import openfl.ui.MultitouchInputModeTest;
import openfl.ui.MultitouchTest;
import openfl.utils.ByteArrayTest;
import openfl.utils.CompressionAlgorithmTest;
import openfl.utils.DictionaryTest;
import openfl.utils.EndianTest;
import openfl.VectorTest;

/**
 * Auto generated Test Suite for MassiveUnit.
 * Refer to munit command line tool for more information (haxelib run munit)
 */
class UnitTestSuite extends massive.munit.TestSuite
{
	public function new()
	{
		super();

		add(openfl.desktop.ClipboardFormatsTest);
		add(openfl.desktop.ClipboardTest);
		add(openfl.desktop.ClipboardTransferModeTest);
		add(openfl.display.BitmapDataChannelTest);
		add(openfl.display.BlendModeTest);
		add(openfl.display.CapsStyleTest);
		add(openfl.display.GradientTypeTest);
		add(openfl.display.GraphicsEndFillTest);
		add(openfl.display.GraphicsGradientFillTest);
		add(openfl.display.GraphicsPathCommandTest);
		add(openfl.display.GraphicsPathTest);
		add(openfl.display.GraphicsPathWindingTest);
		add(openfl.display.GraphicsSolidFillTest);
		add(openfl.display.GraphicsStrokeTest);
		add(openfl.display.InterpolationMethodTest);
		add(openfl.display.JointStyleTest);
		add(openfl.display.JPEGEncoderOptionsTest);
		add(openfl.display.LineScaleModeTest);
		add(openfl.display.PixelSnappingTest);
		add(openfl.display.PNGEncoderOptionsTest);
		add(openfl.display.ShaderParameterTypeTest);
		add(openfl.display.ShaderPrecisionTest);
		add(openfl.display.SpreadMethodTest);
		add(openfl.display.StageAlignTest);
		add(openfl.display.StageDisplayStateTest);
		add(openfl.display.StageQualityTest);
		add(openfl.display.StageScaleModeTest);
		add(openfl.display.TriangleCullingTest);
		add(openfl.display3D.Context3DBlendFactorTest);
		add(openfl.display3D.Context3DBufferUsageTest);
		add(openfl.display3D.Context3DClearMaskTest);
		add(openfl.display3D.Context3DCompareModeTest);
		add(openfl.display3D.Context3DMipFilterTest);
		add(openfl.display3D.Context3DProfileTest);
		add(openfl.display3D.Context3DProgramTypeTest);
		add(openfl.display3D.Context3DRenderModeTest);
		add(openfl.display3D.Context3DStencilActionTest);
		add(openfl.display3D.Context3DTextureFilterTest);
		add(openfl.display3D.Context3DTextureFormatTest);
		add(openfl.display3D.Context3DTriangleFaceTest);
		add(openfl.display3D.Context3DVertexBufferFormatTest);
		add(openfl.display3D.Context3DWrapModeTest);
		add(openfl.errors.ArgumentErrorTest);
		add(openfl.errors.EOFErrorTest);
		add(openfl.errors.ErrorTest);
		add(openfl.errors.IllegalOperationErrorTest);
		add(openfl.errors.IOErrorTest);
		add(openfl.errors.RangeErrorTest);
		add(openfl.errors.SecurityErrorTest);
		add(openfl.errors.TypeErrorTest);
		add(openfl.external.ExternalInterfaceTest);
		add(openfl.filters.BitmapFilterTypeTest);
		add(openfl.geom.ColorTransformTest);
		add(openfl.geom.Matrix3DTest);
		add(openfl.geom.MatrixTest);
		add(openfl.geom.Orientation3DTest);
		add(openfl.geom.PointTest);
		add(openfl.geom.RectangleTest);
		add(openfl.geom.Utils3DTest);
		add(openfl.geom.Vector3DTest);
		add(openfl.LibTest);
		add(openfl.media.SoundChannelTest);
		add(openfl.media.SoundLoaderContextTest);
		add(openfl.media.SoundTransformTest);
		add(openfl.MemoryTest);
		add(openfl.net.SharedObjectFlushStatusTest);
		add(openfl.net.URLLoaderDataFormatTest);
		add(openfl.net.URLRequestHeaderTest);
		add(openfl.net.URLRequestMethodTest);
		add(openfl.net.URLRequestTest);
		add(openfl.net.URLVariablesTest);
		add(openfl.system.ApplicationDomainTest);
		add(openfl.system.CapabilitiesTest);
		add(openfl.system.LoaderContextTest);
		add(openfl.system.SecurityDomainTest);
		add(openfl.system.SystemTest);
		add(openfl.text.AntiAliasTypeTest);
		add(openfl.text.FontStyleTest);
		add(openfl.text.FontTypeTest);
		add(openfl.text.GridFitTypeTest);
		add(openfl.text.TextFieldAutoSizeTest);
		add(openfl.text.TextFieldTypeTest);
		add(openfl.text.TextFormatAlignTest);
		add(openfl.text.TextFormatTest);
		add(openfl.text.TextLineMetricsTest);
		add(openfl.ui.KeyboardTest);
		add(openfl.ui.MouseTest);
		add(openfl.ui.MultitouchInputModeTest);
		add(openfl.ui.MultitouchTest);
		add(openfl.utils.ByteArrayTest);
		add(openfl.utils.CompressionAlgorithmTest);
		add(openfl.utils.DictionaryTest);
		add(openfl.utils.EndianTest);
		add(openfl.VectorTest);
	}
}
