
declare namespace openfl.utils {

export class AGALMiniAssembler {

	constructor(debugging?:any);
	agalcode:any;
	error:any;
	verbose:any;
	debugEnabled:any;
	assemble2(context3D:any, version:any, vertexSource:any, fragmentSource:any):any;
	assemble(mode:any, source:any, version?:any, ignoreLimits?:any):any;
	initregmap(version:any, ignorelimits:any):any;
	match(value:any, reg:any):any;
	static OPMAP:any;
	static REGMAP:any;
	static SAMPLEMAP:any;
	static MAX_NESTING:any;
	static MAX_OPCODES:any;
	static FRAGMENT:any;
	static VERTEX:any;
	static SAMPLER_TYPE_SHIFT:any;
	static SAMPLER_DIM_SHIFT:any;
	static SAMPLER_SPECIAL_SHIFT:any;
	static SAMPLER_REPEAT_SHIFT:any;
	static SAMPLER_MIPMAP_SHIFT:any;
	static SAMPLER_FILTER_SHIFT:any;
	static REG_WRITE:any;
	static REG_READ:any;
	static REG_FRAG:any;
	static REG_VERT:any;
	static OP_SCALAR:any;
	static OP_SPECIAL_TEX:any;
	static OP_SPECIAL_MATRIX:any;
	static OP_FRAG_ONLY:any;
	static OP_VERT_ONLY:any;
	static OP_NO_DEST:any;
	static OP_VERSION2:any;
	static OP_INCNEST:any;
	static OP_DECNEST:any;
	static MOV:any;
	static ADD:any;
	static SUB:any;
	static MUL:any;
	static DIV:any;
	static RCP:any;
	static MIN:any;
	static MAX:any;
	static FRC:any;
	static SQT:any;
	static RSQ:any;
	static POW:any;
	static LOG:any;
	static EXP:any;
	static NRM:any;
	static SIN:any;
	static COS:any;
	static CRS:any;
	static DP3:any;
	static DP4:any;
	static ABS:any;
	static NEG:any;
	static SAT:any;
	static M33:any;
	static M44:any;
	static M34:any;
	static DDX:any;
	static DDY:any;
	static IFE:any;
	static INE:any;
	static IFG:any;
	static IFL:any;
	static IEG:any;
	static IEL:any;
	static ELS:any;
	static EIF:any;
	static TED:any;
	static KIL:any;
	static TEX:any;
	static SGE:any;
	static SLT:any;
	static SGN:any;
	static SEQ:any;
	static SNE:any;
	static VA:any;
	static VC:any;
	static VT:any;
	static VO:any;
	static VI:any;
	static FC:any;
	static FT:any;
	static FS:any;
	static FO:any;
	static FD:any;
	static IID:any;
	static D2:any;
	static D3:any;
	static CUBE:any;
	static MIPNEAREST:any;
	static MIPLINEAR:any;
	static MIPNONE:any;
	static NOMIP:any;
	static NEAREST:any;
	static LINEAR:any;
	static ANISOTROPIC2X:any;
	static ANISOTROPIC4X:any;
	static ANISOTROPIC8X:any;
	static ANISOTROPIC16X:any;
	static CENTROID:any;
	static SINGLE:any;
	static IGNORESAMPLER:any;
	static REPEAT:any;
	static WRAP:any;
	static CLAMP:any;
	static REPEAT_U_CLAMP_V:any;
	static CLAMP_U_REPEAT_V:any;
	static RGBA:any;
	static COMPRESSED:any;
	static COMPRESSEDALPHA:any;
	static DXT1:any;
	static DXT5:any;
	static VIDEO:any;
	static initialized:any;
	static init():any;


}

}

export default openfl.utils.AGALMiniAssembler;