// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var SWFLiteFB = SWFLiteFB || {};

/**
 * @enum
 */
SWFLiteFB.BlendMode = {
  ADD: 0,
  ALPHA: 1,
  DARKEN: 2,
  DIFFERENCE: 3,
  ERASE: 4,
  HARDLIGHT: 5,
  INVERT: 6,
  LAYER: 7,
  LIGHTEN: 8,
  MULTIPLY: 9,
  NORMAL: 10,
  OVERLAY: 11,
  SCREEN: 12,
  SHADER: 13,
  SUBTRACT: 14
};

/**
 * @enum
 */
SWFLiteFB.FrameObjectType = {
  CREATE: 0,
  UPDATE: 1,
  DESTROY: 2
};

/**
 * @enum
 */
SWFLiteFB.FilterType = {
  BlurFilter: 0,
  ColorMatrixFilter: 1,
  DropShadowFilter: 2,
  GlowFilter: 3
};

/**
 * @constructor
 */
SWFLiteFB.Point = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {SWFLiteFB.Point}
 */
SWFLiteFB.Point.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
SWFLiteFB.Point.prototype.x = function() {
  return this.bb.readFloat64(this.bb_pos);
};

/**
 * @returns {number}
 */
SWFLiteFB.Point.prototype.y = function() {
  return this.bb.readFloat64(this.bb_pos + 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} x
 * @param {number} y
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.Point.createPoint = function(builder, x, y) {
  builder.prep(8, 16);
  builder.writeFloat64(y);
  builder.writeFloat64(x);
  return builder.offset();
};

/**
 * @constructor
 */
SWFLiteFB.Matrix = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {SWFLiteFB.Matrix}
 */
SWFLiteFB.Matrix.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
SWFLiteFB.Matrix.prototype.a = function() {
  return this.bb.readFloat64(this.bb_pos);
};

/**
 * @returns {number}
 */
SWFLiteFB.Matrix.prototype.b = function() {
  return this.bb.readFloat64(this.bb_pos + 8);
};

/**
 * @returns {number}
 */
SWFLiteFB.Matrix.prototype.c = function() {
  return this.bb.readFloat64(this.bb_pos + 16);
};

/**
 * @returns {number}
 */
SWFLiteFB.Matrix.prototype.d = function() {
  return this.bb.readFloat64(this.bb_pos + 24);
};

/**
 * @returns {number}
 */
SWFLiteFB.Matrix.prototype.tx = function() {
  return this.bb.readFloat64(this.bb_pos + 32);
};

/**
 * @returns {number}
 */
SWFLiteFB.Matrix.prototype.ty = function() {
  return this.bb.readFloat64(this.bb_pos + 40);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} a
 * @param {number} b
 * @param {number} c
 * @param {number} d
 * @param {number} tx
 * @param {number} ty
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.Matrix.createMatrix = function(builder, a, b, c, d, tx, ty) {
  builder.prep(8, 48);
  builder.writeFloat64(ty);
  builder.writeFloat64(tx);
  builder.writeFloat64(d);
  builder.writeFloat64(c);
  builder.writeFloat64(b);
  builder.writeFloat64(a);
  return builder.offset();
};

/**
 * @constructor
 */
SWFLiteFB.SWFLite = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {SWFLiteFB.SWFLite}
 */
SWFLiteFB.SWFLite.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {SWFLiteFB.SWFLite=} obj
 * @returns {SWFLiteFB.SWFLite}
 */
SWFLiteFB.SWFLite.getRootAsSWFLite = function(bb, obj) {
  return (obj || new SWFLiteFB.SWFLite).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
SWFLiteFB.SWFLite.prototype.frameRate = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt16(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {SWFLiteFB.SWFLiteLibrary=} obj
 * @returns {SWFLiteFB.SWFLiteLibrary}
 */
SWFLiteFB.SWFLite.prototype.library = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new SWFLiteFB.SWFLiteLibrary).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
SWFLiteFB.SWFLite.prototype.libraryLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {SWFLiteFB.SpriteSymbol=} obj
 * @returns {SWFLiteFB.SpriteSymbol}
 */
SWFLiteFB.SWFLite.prototype.root = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new SWFLiteFB.SpriteSymbol).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
SWFLiteFB.SWFLite.prototype.rootLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {SWFLiteFB.Symbols=} obj
 * @returns {SWFLiteFB.Symbols}
 */
SWFLiteFB.SWFLite.prototype.symbols = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? (obj || new SWFLiteFB.Symbols).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
SWFLiteFB.SWFLite.prototype.symbolsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {SWFLiteFB.Point=} obj
 * @returns {SWFLiteFB.Point|null}
 */
SWFLiteFB.SWFLite.prototype.frameSizeMinPixel = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? (obj || new SWFLiteFB.Point).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {SWFLiteFB.Point=} obj
 * @returns {SWFLiteFB.Point|null}
 */
SWFLiteFB.SWFLite.prototype.frameSizeMaxPixel = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? (obj || new SWFLiteFB.Point).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
SWFLiteFB.SWFLite.startSWFLite = function(builder) {
  builder.startObject(6);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} frameRate
 */
SWFLiteFB.SWFLite.addFrameRate = function(builder, frameRate) {
  builder.addFieldInt16(0, frameRate, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} libraryOffset
 */
SWFLiteFB.SWFLite.addLibrary = function(builder, libraryOffset) {
  builder.addFieldOffset(1, libraryOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.SWFLite.createLibraryVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
SWFLiteFB.SWFLite.startLibraryVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} rootOffset
 */
SWFLiteFB.SWFLite.addRoot = function(builder, rootOffset) {
  builder.addFieldOffset(2, rootOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.SWFLite.createRootVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
SWFLiteFB.SWFLite.startRootVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} symbolsOffset
 */
SWFLiteFB.SWFLite.addSymbols = function(builder, symbolsOffset) {
  builder.addFieldOffset(3, symbolsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.SWFLite.createSymbolsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
SWFLiteFB.SWFLite.startSymbolsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} frameSizeMinPixelOffset
 */
SWFLiteFB.SWFLite.addFrameSizeMinPixel = function(builder, frameSizeMinPixelOffset) {
  builder.addFieldStruct(4, frameSizeMinPixelOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} frameSizeMaxPixelOffset
 */
SWFLiteFB.SWFLite.addFrameSizeMaxPixel = function(builder, frameSizeMaxPixelOffset) {
  builder.addFieldStruct(5, frameSizeMaxPixelOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.SWFLite.endSWFLite = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
SWFLiteFB.SWFLite.finishSWFLiteBuffer = function(builder, offset) {
  builder.finish(offset);
};

/**
 * @constructor
 */
SWFLiteFB.SWFLiteLibrary = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {SWFLiteFB.SWFLiteLibrary}
 */
SWFLiteFB.SWFLiteLibrary.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {SWFLiteFB.SWFLiteLibrary=} obj
 * @returns {SWFLiteFB.SWFLiteLibrary}
 */
SWFLiteFB.SWFLiteLibrary.getRootAsSWFLiteLibrary = function(bb, obj) {
  return (obj || new SWFLiteFB.SWFLiteLibrary).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {SWFLiteFB.alphaCheckList=} obj
 * @returns {SWFLiteFB.alphaCheckList}
 */
SWFLiteFB.SWFLiteLibrary.prototype.alphaCheck = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new SWFLiteFB.alphaCheckList).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
SWFLiteFB.SWFLiteLibrary.prototype.alphaCheckLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
SWFLiteFB.SWFLiteLibrary.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {number} index
 * @param {SWFLiteFB.imageClassNamesList=} obj
 * @returns {SWFLiteFB.imageClassNamesList}
 */
SWFLiteFB.SWFLiteLibrary.prototype.imageClassNames = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new SWFLiteFB.imageClassNamesList).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
SWFLiteFB.SWFLiteLibrary.prototype.imageClassNamesLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {boolean}
 */
SWFLiteFB.SWFLiteLibrary.prototype.preloading = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
SWFLiteFB.SWFLiteLibrary.prototype.rootPath = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
SWFLiteFB.SWFLiteLibrary.startSWFLiteLibrary = function(builder) {
  builder.startObject(5);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} alphaCheckOffset
 */
SWFLiteFB.SWFLiteLibrary.addAlphaCheck = function(builder, alphaCheckOffset) {
  builder.addFieldOffset(0, alphaCheckOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.SWFLiteLibrary.createAlphaCheckVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
SWFLiteFB.SWFLiteLibrary.startAlphaCheckVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
SWFLiteFB.SWFLiteLibrary.addId = function(builder, idOffset) {
  builder.addFieldOffset(1, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} imageClassNamesOffset
 */
SWFLiteFB.SWFLiteLibrary.addImageClassNames = function(builder, imageClassNamesOffset) {
  builder.addFieldOffset(2, imageClassNamesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.SWFLiteLibrary.createImageClassNamesVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
SWFLiteFB.SWFLiteLibrary.startImageClassNamesVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} preloading
 */
SWFLiteFB.SWFLiteLibrary.addPreloading = function(builder, preloading) {
  builder.addFieldInt8(3, +preloading, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} rootPathOffset
 */
SWFLiteFB.SWFLiteLibrary.addRootPath = function(builder, rootPathOffset) {
  builder.addFieldOffset(4, rootPathOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.SWFLiteLibrary.endSWFLiteLibrary = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
SWFLiteFB.alphaCheckList = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {SWFLiteFB.alphaCheckList}
 */
SWFLiteFB.alphaCheckList.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {SWFLiteFB.alphaCheckList=} obj
 * @returns {SWFLiteFB.alphaCheckList}
 */
SWFLiteFB.alphaCheckList.getRootAsalphaCheckList = function(bb, obj) {
  return (obj || new SWFLiteFB.alphaCheckList).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
SWFLiteFB.alphaCheckList.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {boolean}
 */
SWFLiteFB.alphaCheckList.prototype.value = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {flatbuffers.Builder} builder
 */
SWFLiteFB.alphaCheckList.startalphaCheckList = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
SWFLiteFB.alphaCheckList.addName = function(builder, nameOffset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} value
 */
SWFLiteFB.alphaCheckList.addValue = function(builder, value) {
  builder.addFieldInt8(1, +value, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.alphaCheckList.endalphaCheckList = function(builder) {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // name
  return offset;
};

/**
 * @constructor
 */
SWFLiteFB.imageClassNamesList = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {SWFLiteFB.imageClassNamesList}
 */
SWFLiteFB.imageClassNamesList.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {SWFLiteFB.imageClassNamesList=} obj
 * @returns {SWFLiteFB.imageClassNamesList}
 */
SWFLiteFB.imageClassNamesList.getRootAsimageClassNamesList = function(bb, obj) {
  return (obj || new SWFLiteFB.imageClassNamesList).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
SWFLiteFB.imageClassNamesList.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
SWFLiteFB.imageClassNamesList.prototype.value = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
SWFLiteFB.imageClassNamesList.startimageClassNamesList = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
SWFLiteFB.imageClassNamesList.addName = function(builder, nameOffset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} valueOffset
 */
SWFLiteFB.imageClassNamesList.addValue = function(builder, valueOffset) {
  builder.addFieldOffset(1, valueOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.imageClassNamesList.endimageClassNamesList = function(builder) {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // name
  return offset;
};

/**
 * @constructor
 */
SWFLiteFB.SpriteSymbol = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {SWFLiteFB.SpriteSymbol}
 */
SWFLiteFB.SpriteSymbol.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {SWFLiteFB.SpriteSymbol=} obj
 * @returns {SWFLiteFB.SpriteSymbol}
 */
SWFLiteFB.SpriteSymbol.getRootAsSpriteSymbol = function(bb, obj) {
  return (obj || new SWFLiteFB.SpriteSymbol).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
SWFLiteFB.SpriteSymbol.prototype.baseClassName = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {number} index
 * @param {SWFLiteFB.Frame=} obj
 * @returns {SWFLiteFB.Frame}
 */
SWFLiteFB.SpriteSymbol.prototype.frames = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new SWFLiteFB.Frame).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
SWFLiteFB.SpriteSymbol.prototype.framesLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
SWFLiteFB.SpriteSymbol.startSpriteSymbol = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} baseClassNameOffset
 */
SWFLiteFB.SpriteSymbol.addBaseClassName = function(builder, baseClassNameOffset) {
  builder.addFieldOffset(0, baseClassNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} framesOffset
 */
SWFLiteFB.SpriteSymbol.addFrames = function(builder, framesOffset) {
  builder.addFieldOffset(1, framesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.SpriteSymbol.createFramesVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
SWFLiteFB.SpriteSymbol.startFramesVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.SpriteSymbol.endSpriteSymbol = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
SWFLiteFB.Frame = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {SWFLiteFB.Frame}
 */
SWFLiteFB.Frame.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {SWFLiteFB.Frame=} obj
 * @returns {SWFLiteFB.Frame}
 */
SWFLiteFB.Frame.getRootAsFrame = function(bb, obj) {
  return (obj || new SWFLiteFB.Frame).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
SWFLiteFB.Frame.prototype.labels = function(index, optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
SWFLiteFB.Frame.prototype.labelsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
SWFLiteFB.Frame.prototype.label = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {number} index
 * @param {SWFLiteFB.frameObject=} obj
 * @returns {SWFLiteFB.frameObject}
 */
SWFLiteFB.Frame.prototype.objects = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new SWFLiteFB.frameObject).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
SWFLiteFB.Frame.prototype.objectsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
SWFLiteFB.Frame.prototype.script = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
SWFLiteFB.Frame.prototype.scriptSource = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
SWFLiteFB.Frame.startFrame = function(builder) {
  builder.startObject(5);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} labelsOffset
 */
SWFLiteFB.Frame.addLabels = function(builder, labelsOffset) {
  builder.addFieldOffset(0, labelsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.Frame.createLabelsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
SWFLiteFB.Frame.startLabelsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} labelOffset
 */
SWFLiteFB.Frame.addLabel = function(builder, labelOffset) {
  builder.addFieldOffset(1, labelOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectsOffset
 */
SWFLiteFB.Frame.addObjects = function(builder, objectsOffset) {
  builder.addFieldOffset(2, objectsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.Frame.createObjectsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
SWFLiteFB.Frame.startObjectsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} scriptOffset
 */
SWFLiteFB.Frame.addScript = function(builder, scriptOffset) {
  builder.addFieldOffset(3, scriptOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} scriptSourceOffset
 */
SWFLiteFB.Frame.addScriptSource = function(builder, scriptSourceOffset) {
  builder.addFieldOffset(4, scriptSourceOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.Frame.endFrame = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
SWFLiteFB.frameObject = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {SWFLiteFB.frameObject}
 */
SWFLiteFB.frameObject.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {SWFLiteFB.frameObject=} obj
 * @returns {SWFLiteFB.frameObject}
 */
SWFLiteFB.frameObject.getRootAsframeObject = function(bb, obj) {
  return (obj || new SWFLiteFB.frameObject).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {SWFLiteFB.CurrentBlendMode=} obj
 * @returns {SWFLiteFB.CurrentBlendMode|null}
 */
SWFLiteFB.frameObject.prototype.blendMode = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new SWFLiteFB.CurrentBlendMode).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {SWFLiteFB.CurrentCacheAsBitmap=} obj
 * @returns {SWFLiteFB.CurrentCacheAsBitmap|null}
 */
SWFLiteFB.frameObject.prototype.cacheAsBitmap = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new SWFLiteFB.CurrentCacheAsBitmap).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @returns {number}
 */
SWFLiteFB.frameObject.prototype.clipDepth = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt16(this.bb_pos + offset) : 0;
};

/**
 * @param {SWFLiteFB.CurrentColorTransform=} obj
 * @returns {SWFLiteFB.CurrentColorTransform|null}
 */
SWFLiteFB.frameObject.prototype.colorTransform = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? (obj || new SWFLiteFB.CurrentColorTransform).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @returns {number}
 */
SWFLiteFB.frameObject.prototype.depth = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readInt16(this.bb_pos + offset) : 0;
};

/**
 * @param {SWFLiteFB.CurrentFilterTypes=} obj
 * @returns {SWFLiteFB.CurrentFilterTypes|null}
 */
SWFLiteFB.frameObject.prototype.filters = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? (obj || new SWFLiteFB.CurrentFilterTypes).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @returns {number}
 */
SWFLiteFB.frameObject.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {SWFLiteFB.CurrentMatrix=} obj
 * @returns {SWFLiteFB.CurrentMatrix|null}
 */
SWFLiteFB.frameObject.prototype.matrix = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? (obj || new SWFLiteFB.CurrentMatrix).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
SWFLiteFB.frameObject.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 20);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
SWFLiteFB.frameObject.prototype.symbol = function() {
  var offset = this.bb.__offset(this.bb_pos, 22);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {SWFLiteFB.CurrentFrameObjectType=} obj
 * @returns {SWFLiteFB.CurrentFrameObjectType|null}
 */
SWFLiteFB.frameObject.prototype.type = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 24);
  return offset ? (obj || new SWFLiteFB.CurrentFrameObjectType).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {SWFLiteFB.CurrentVisible=} obj
 * @returns {SWFLiteFB.CurrentVisible|null}
 */
SWFLiteFB.frameObject.prototype.visible = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 26);
  return offset ? (obj || new SWFLiteFB.CurrentVisible).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
SWFLiteFB.frameObject.startframeObject = function(builder) {
  builder.startObject(12);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} blendModeOffset
 */
SWFLiteFB.frameObject.addBlendMode = function(builder, blendModeOffset) {
  builder.addFieldOffset(0, blendModeOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} cacheAsBitmapOffset
 */
SWFLiteFB.frameObject.addCacheAsBitmap = function(builder, cacheAsBitmapOffset) {
  builder.addFieldOffset(1, cacheAsBitmapOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} clipDepth
 */
SWFLiteFB.frameObject.addClipDepth = function(builder, clipDepth) {
  builder.addFieldInt16(2, clipDepth, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} colorTransformOffset
 */
SWFLiteFB.frameObject.addColorTransform = function(builder, colorTransformOffset) {
  builder.addFieldOffset(3, colorTransformOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} depth
 */
SWFLiteFB.frameObject.addDepth = function(builder, depth) {
  builder.addFieldInt16(4, depth, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} filtersOffset
 */
SWFLiteFB.frameObject.addFilters = function(builder, filtersOffset) {
  builder.addFieldOffset(5, filtersOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} id
 */
SWFLiteFB.frameObject.addId = function(builder, id) {
  builder.addFieldInt32(6, id, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} matrixOffset
 */
SWFLiteFB.frameObject.addMatrix = function(builder, matrixOffset) {
  builder.addFieldOffset(7, matrixOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
SWFLiteFB.frameObject.addName = function(builder, nameOffset) {
  builder.addFieldOffset(8, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} symbol
 */
SWFLiteFB.frameObject.addSymbol = function(builder, symbol) {
  builder.addFieldInt32(9, symbol, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} typeOffset
 */
SWFLiteFB.frameObject.addType = function(builder, typeOffset) {
  builder.addFieldOffset(10, typeOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} visibleOffset
 */
SWFLiteFB.frameObject.addVisible = function(builder, visibleOffset) {
  builder.addFieldOffset(11, visibleOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.frameObject.endframeObject = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
SWFLiteFB.CurrentBlendMode = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {SWFLiteFB.CurrentBlendMode}
 */
SWFLiteFB.CurrentBlendMode.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {SWFLiteFB.CurrentBlendMode=} obj
 * @returns {SWFLiteFB.CurrentBlendMode}
 */
SWFLiteFB.CurrentBlendMode.getRootAsCurrentBlendMode = function(bb, obj) {
  return (obj || new SWFLiteFB.CurrentBlendMode).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {SWFLiteFB.BlendMode}
 */
SWFLiteFB.CurrentBlendMode.prototype.blendMode = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {SWFLiteFB.BlendMode} */ (this.bb.readInt8(this.bb_pos + offset)) : SWFLiteFB.BlendMode.ADD;
};

/**
 * @param {flatbuffers.Builder} builder
 */
SWFLiteFB.CurrentBlendMode.startCurrentBlendMode = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {SWFLiteFB.BlendMode} blendMode
 */
SWFLiteFB.CurrentBlendMode.addBlendMode = function(builder, blendMode) {
  builder.addFieldInt8(0, blendMode, SWFLiteFB.BlendMode.ADD);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.CurrentBlendMode.endCurrentBlendMode = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
SWFLiteFB.CurrentCacheAsBitmap = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {SWFLiteFB.CurrentCacheAsBitmap}
 */
SWFLiteFB.CurrentCacheAsBitmap.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {SWFLiteFB.CurrentCacheAsBitmap=} obj
 * @returns {SWFLiteFB.CurrentCacheAsBitmap}
 */
SWFLiteFB.CurrentCacheAsBitmap.getRootAsCurrentCacheAsBitmap = function(bb, obj) {
  return (obj || new SWFLiteFB.CurrentCacheAsBitmap).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {boolean}
 */
SWFLiteFB.CurrentCacheAsBitmap.prototype.cacheAsBitmap = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {flatbuffers.Builder} builder
 */
SWFLiteFB.CurrentCacheAsBitmap.startCurrentCacheAsBitmap = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} cacheAsBitmap
 */
SWFLiteFB.CurrentCacheAsBitmap.addCacheAsBitmap = function(builder, cacheAsBitmap) {
  builder.addFieldInt8(0, +cacheAsBitmap, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.CurrentCacheAsBitmap.endCurrentCacheAsBitmap = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
SWFLiteFB.CurrentFilterTypes = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {SWFLiteFB.CurrentFilterTypes}
 */
SWFLiteFB.CurrentFilterTypes.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {SWFLiteFB.CurrentFilterTypes=} obj
 * @returns {SWFLiteFB.CurrentFilterTypes}
 */
SWFLiteFB.CurrentFilterTypes.getRootAsCurrentFilterTypes = function(bb, obj) {
  return (obj || new SWFLiteFB.CurrentFilterTypes).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @returns {SWFLiteFB.FilterType}
 */
SWFLiteFB.CurrentFilterTypes.prototype.filterTypes = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {SWFLiteFB.FilterType} */ (this.bb.readInt8(this.bb.__vector(this.bb_pos + offset) + index)) : /** @type {SWFLiteFB.FilterType} */ (0);
};

/**
 * @returns {number}
 */
SWFLiteFB.CurrentFilterTypes.prototype.filterTypesLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Int8Array}
 */
SWFLiteFB.CurrentFilterTypes.prototype.filterTypesArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? new Int8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
SWFLiteFB.CurrentFilterTypes.startCurrentFilterTypes = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} filterTypesOffset
 */
SWFLiteFB.CurrentFilterTypes.addFilterTypes = function(builder, filterTypesOffset) {
  builder.addFieldOffset(0, filterTypesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<SWFLiteFB.FilterType>} data
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.CurrentFilterTypes.createFilterTypesVector = function(builder, data) {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
SWFLiteFB.CurrentFilterTypes.startFilterTypesVector = function(builder, numElems) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.CurrentFilterTypes.endCurrentFilterTypes = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
SWFLiteFB.ColorTransform = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {SWFLiteFB.ColorTransform}
 */
SWFLiteFB.ColorTransform.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
SWFLiteFB.ColorTransform.prototype.alphaMultiplier = function() {
  return this.bb.readFloat64(this.bb_pos);
};

/**
 * @returns {number}
 */
SWFLiteFB.ColorTransform.prototype.alphaOffset = function() {
  return this.bb.readFloat64(this.bb_pos + 8);
};

/**
 * @returns {number}
 */
SWFLiteFB.ColorTransform.prototype.blueMultiplier = function() {
  return this.bb.readFloat64(this.bb_pos + 16);
};

/**
 * @returns {number}
 */
SWFLiteFB.ColorTransform.prototype.blueOffset = function() {
  return this.bb.readFloat64(this.bb_pos + 24);
};

/**
 * @returns {number}
 */
SWFLiteFB.ColorTransform.prototype.greenMultiplier = function() {
  return this.bb.readFloat64(this.bb_pos + 32);
};

/**
 * @returns {number}
 */
SWFLiteFB.ColorTransform.prototype.greenOffset = function() {
  return this.bb.readFloat64(this.bb_pos + 40);
};

/**
 * @returns {number}
 */
SWFLiteFB.ColorTransform.prototype.redMultiplier = function() {
  return this.bb.readFloat64(this.bb_pos + 48);
};

/**
 * @returns {number}
 */
SWFLiteFB.ColorTransform.prototype.redOffset = function() {
  return this.bb.readFloat64(this.bb_pos + 56);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} alphaMultiplier
 * @param {number} alphaOffset
 * @param {number} blueMultiplier
 * @param {number} blueOffset
 * @param {number} greenMultiplier
 * @param {number} greenOffset
 * @param {number} redMultiplier
 * @param {number} redOffset
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.ColorTransform.createColorTransform = function(builder, alphaMultiplier, alphaOffset, blueMultiplier, blueOffset, greenMultiplier, greenOffset, redMultiplier, redOffset) {
  builder.prep(8, 64);
  builder.writeFloat64(redOffset);
  builder.writeFloat64(redMultiplier);
  builder.writeFloat64(greenOffset);
  builder.writeFloat64(greenMultiplier);
  builder.writeFloat64(blueOffset);
  builder.writeFloat64(blueMultiplier);
  builder.writeFloat64(alphaOffset);
  builder.writeFloat64(alphaMultiplier);
  return builder.offset();
};

/**
 * @constructor
 */
SWFLiteFB.CurrentColorTransform = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {SWFLiteFB.CurrentColorTransform}
 */
SWFLiteFB.CurrentColorTransform.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {SWFLiteFB.CurrentColorTransform=} obj
 * @returns {SWFLiteFB.CurrentColorTransform}
 */
SWFLiteFB.CurrentColorTransform.getRootAsCurrentColorTransform = function(bb, obj) {
  return (obj || new SWFLiteFB.CurrentColorTransform).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {SWFLiteFB.ColorTransform=} obj
 * @returns {SWFLiteFB.ColorTransform|null}
 */
SWFLiteFB.CurrentColorTransform.prototype.colorTransform = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new SWFLiteFB.ColorTransform).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
SWFLiteFB.CurrentColorTransform.startCurrentColorTransform = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} colorTransformOffset
 */
SWFLiteFB.CurrentColorTransform.addColorTransform = function(builder, colorTransformOffset) {
  builder.addFieldStruct(0, colorTransformOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.CurrentColorTransform.endCurrentColorTransform = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
SWFLiteFB.CurrentMatrix = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {SWFLiteFB.CurrentMatrix}
 */
SWFLiteFB.CurrentMatrix.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {SWFLiteFB.CurrentMatrix=} obj
 * @returns {SWFLiteFB.CurrentMatrix}
 */
SWFLiteFB.CurrentMatrix.getRootAsCurrentMatrix = function(bb, obj) {
  return (obj || new SWFLiteFB.CurrentMatrix).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {SWFLiteFB.Matrix=} obj
 * @returns {SWFLiteFB.Matrix|null}
 */
SWFLiteFB.CurrentMatrix.prototype.matrix = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new SWFLiteFB.Matrix).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
SWFLiteFB.CurrentMatrix.startCurrentMatrix = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} matrixOffset
 */
SWFLiteFB.CurrentMatrix.addMatrix = function(builder, matrixOffset) {
  builder.addFieldStruct(0, matrixOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.CurrentMatrix.endCurrentMatrix = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
SWFLiteFB.CurrentFrameObjectType = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {SWFLiteFB.CurrentFrameObjectType}
 */
SWFLiteFB.CurrentFrameObjectType.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {SWFLiteFB.CurrentFrameObjectType=} obj
 * @returns {SWFLiteFB.CurrentFrameObjectType}
 */
SWFLiteFB.CurrentFrameObjectType.getRootAsCurrentFrameObjectType = function(bb, obj) {
  return (obj || new SWFLiteFB.CurrentFrameObjectType).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {SWFLiteFB.FrameObjectType}
 */
SWFLiteFB.CurrentFrameObjectType.prototype.frameObjectType = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {SWFLiteFB.FrameObjectType} */ (this.bb.readInt8(this.bb_pos + offset)) : SWFLiteFB.FrameObjectType.CREATE;
};

/**
 * @param {flatbuffers.Builder} builder
 */
SWFLiteFB.CurrentFrameObjectType.startCurrentFrameObjectType = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {SWFLiteFB.FrameObjectType} frameObjectType
 */
SWFLiteFB.CurrentFrameObjectType.addFrameObjectType = function(builder, frameObjectType) {
  builder.addFieldInt8(0, frameObjectType, SWFLiteFB.FrameObjectType.CREATE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.CurrentFrameObjectType.endCurrentFrameObjectType = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
SWFLiteFB.CurrentVisible = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {SWFLiteFB.CurrentVisible}
 */
SWFLiteFB.CurrentVisible.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {SWFLiteFB.CurrentVisible=} obj
 * @returns {SWFLiteFB.CurrentVisible}
 */
SWFLiteFB.CurrentVisible.getRootAsCurrentVisible = function(bb, obj) {
  return (obj || new SWFLiteFB.CurrentVisible).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {SWFLiteFB.CurrentVisible=} obj
 * @returns {SWFLiteFB.CurrentVisible|null}
 */
SWFLiteFB.CurrentVisible.prototype.visible = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new SWFLiteFB.CurrentVisible).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
SWFLiteFB.CurrentVisible.startCurrentVisible = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} visibleOffset
 */
SWFLiteFB.CurrentVisible.addVisible = function(builder, visibleOffset) {
  builder.addFieldOffset(0, visibleOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.CurrentVisible.endCurrentVisible = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
SWFLiteFB.Symbols = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {SWFLiteFB.Symbols}
 */
SWFLiteFB.Symbols.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {SWFLiteFB.Symbols=} obj
 * @returns {SWFLiteFB.Symbols}
 */
SWFLiteFB.Symbols.getRootAsSymbols = function(bb, obj) {
  return (obj || new SWFLiteFB.Symbols).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
SWFLiteFB.Symbols.prototype.key = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
SWFLiteFB.Symbols.prototype.className = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
SWFLiteFB.Symbols.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
SWFLiteFB.Symbols.startSymbols = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} key
 */
SWFLiteFB.Symbols.addKey = function(builder, key) {
  builder.addFieldInt32(0, key, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} classNameOffset
 */
SWFLiteFB.Symbols.addClassName = function(builder, classNameOffset) {
  builder.addFieldOffset(1, classNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} id
 */
SWFLiteFB.Symbols.addId = function(builder, id) {
  builder.addFieldInt32(2, id, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
SWFLiteFB.Symbols.endSymbols = function(builder) {
  var offset = builder.endObject();
  return offset;
};

// Exports for Node.js and RequireJS
this.SWFLiteFB = SWFLiteFB;
