import massive.munit.TestSuite;

import openfl.VectorTest;
import openfl.filters.BitmapFilterTypeTest;
import openfl.filters.BitmapFilterTest;
import openfl.filters.BlurFilterTest;
import openfl.filters.DropShadowFilterTest;
import openfl.filters.ColorMatrixFilterTest;
import openfl.filters.GlowFilterTest;
import openfl.events.SampleDataEventTest;
import openfl.events.IOErrorEventTest;
import openfl.events.ErrorEventTest;
import openfl.events.TouchEventTest;
import openfl.events.FocusEventTest;
import openfl.events.EventDispatcherTest;
import openfl.events.MouseEventTest;
import openfl.events.ProgressEventTest;
import openfl.events.JoystickEventTest;
import openfl.events.AccelerometerEventTest;
import openfl.events.TextEventTest;
import openfl.events.KeyboardEventTest;
import openfl.events.EventPhaseTest;
import openfl.events.SystemEventTest;
import openfl.events.EventTest;
import openfl.events.TimerEventTest;
import openfl.events.HTTPStatusEventTest;
import openfl.events.SecurityErrorEventTest;
import openfl.MemoryTest;
import openfl.LibTest;
import openfl.errors.ErrorTest;
import openfl.errors.SecurityErrorTest;
import openfl.errors.RangeErrorTest;
import openfl.errors.TypeErrorTest;
import openfl.errors.EOFErrorTest;
import openfl.errors.ArgumentErrorTest;
import openfl.errors.IllegalOperationErrorTest;
import openfl.system.ApplicationDomainTest;
import openfl.system.SecurityDomainTest;
import openfl.system.LoaderContextTest;
import openfl.system.CapabilitiesTest;
import openfl.system.SystemTest;
import openfl.display.DisplayObjectContainerTest;
import openfl.display.StageScaleModeTest;
import openfl.display.GraphicsPathWindingTest;
import openfl.display.StageAlignTest;
import openfl.display.StageDisplayStateTest;
import openfl.display.GraphicsSolidFillTest;
import openfl.display.GraphicsPathCommandTest;
import openfl.display.StageTest;
import openfl.display.SpriteTest;
import openfl.display.GraphicsEndFillTest;
import openfl.display.GraphicsTest;
import openfl.display.GradientTypeTest;
import openfl.display.LineScaleModeTest;
import openfl.display.DisplayObjectTest;
import openfl.display.LoaderTest;
import openfl.display.GraphicsStrokeTest;
import openfl.display.DirectRendererTest;
import openfl.display.StageQualityTest;
import openfl.display.JointStyleTest;
import openfl.display.BitmapDataChannelTest;
import openfl.display.BitmapDataTest;
import openfl.display.LoaderInfoTest;
import openfl.display.FPSTest;
import openfl.display.TriangleCullingTest;
import openfl.display.SimpleButtonTest;
import openfl.display.GraphicsGradientFillTest;
import openfl.display.BitmapTest;
import openfl.display.InteractiveObjectTest;
import openfl.display.PixelSnappingTest;
import openfl.display.CapsStyleTest;
import openfl.display.GraphicsBitmapFillTest;
import openfl.display.BlendModeTest;
import openfl.display.GraphicsPathTest;
import openfl.display.InterpolationMethodTest;
import openfl.display.SpreadMethodTest;
import openfl.display.MovieClipTest;
import openfl.display.TilesheetTest;
import openfl.display.ShapeTest;
import openfl.display.OpenGLViewTest;
import openfl.media.ID3InfoTest;
import openfl.media.SoundTransformTest;
import openfl.media.SoundLoaderContextTest;
import openfl.media.SoundChannelTest;
import openfl.media.SoundTest;
import openfl.text.TextLineMetricsTest;
import openfl.text.TextFormatTest;
import openfl.text.FontStyleTest;
import openfl.text.TextFormatAlignTest;
import openfl.text.TextFieldTypeTest;
import openfl.text.GridFitTypeTest;
import openfl.text.FontTypeTest;
import openfl.text.AntiAliasTypeTest;
import openfl.text.TextFieldAutoSizeTest;
import openfl.text.TextFieldTest;
import openfl.text.FontTest;
import openfl.AssetsTest;
import openfl.ui.MultitouchTest;
import openfl.ui.MouseTest;
import openfl.ui.MultitouchInputModeTest;
import openfl.ui.KeyboardTest;
import openfl.geom.ColorTransformTest;
import openfl.geom.Vector3DTest;
import openfl.geom.MatrixTest;
import openfl.geom.Matrix3DTest;
import openfl.geom.RectangleTest;
import openfl.geom.TransformTest;
import openfl.geom.PointTest;
import openfl.utils.EndianTest;
import openfl.utils.UInt8ArrayTest;
import openfl.utils.Int32ArrayTest;
import openfl.utils.Int16ArrayTest;
import openfl.utils.Float32ArrayTest;
import openfl.utils.TimerTest;
import openfl.utils.ByteArrayTest;
import openfl.utils.ArrayBufferViewTest;
import openfl.utils.ArrayBufferTest;
import openfl.utils.CompressionAlgorithmTest;
import openfl.gl.GLUniformLocationTest;
import openfl.gl.GLActiveInfoTest;
import openfl.gl.GLTextureTest;
import openfl.gl.GLContextAttributesTest;
import openfl.gl.GLRenderbufferTest;
import openfl.gl.GLFramebufferTest;
import openfl.gl.GLBufferTest;
import openfl.gl.GLProgramTest;
import openfl.gl.GLShaderTest;
import openfl.gl.GLTest;
import openfl.gl.GLObjectTest;
import openfl.sensors.AccelerometerTest;
import openfl.net.URLRequestTest;
import openfl.net.URLLoaderTest;
import openfl.net.URLRequestHeaderTest;
import openfl.net.SharedObjectFlushStatusTest;
import openfl.net.URLRequestMethodTest;
import openfl.net.URLVariablesTest;
import openfl.net.URLLoaderDataFormatTest;
import openfl.net.SharedObjectTest;
import openfl.external.ExternalInterfaceTest;

/**
 * Auto generated Test Suite for MassiveUnit.
 * Refer to munit command line tool for more information (haxelib run munit)
 */

class TestSuite extends massive.munit.TestSuite
{		

	public function new()
	{
		super();

		add(openfl.VectorTest);
		add(openfl.filters.BitmapFilterTypeTest);
		add(openfl.filters.BitmapFilterTest);
		add(openfl.filters.BlurFilterTest);
		add(openfl.filters.DropShadowFilterTest);
		add(openfl.filters.ColorMatrixFilterTest);
		add(openfl.filters.GlowFilterTest);
		add(openfl.events.SampleDataEventTest);
		add(openfl.events.IOErrorEventTest);
		add(openfl.events.ErrorEventTest);
		add(openfl.events.TouchEventTest);
		add(openfl.events.FocusEventTest);
		add(openfl.events.EventDispatcherTest);
		add(openfl.events.MouseEventTest);
		add(openfl.events.ProgressEventTest);
		add(openfl.events.JoystickEventTest);
		add(openfl.events.AccelerometerEventTest);
		add(openfl.events.TextEventTest);
		add(openfl.events.KeyboardEventTest);
		add(openfl.events.EventPhaseTest);
		add(openfl.events.SystemEventTest);
		add(openfl.events.EventTest);
		add(openfl.events.TimerEventTest);
		add(openfl.events.HTTPStatusEventTest);
		add(openfl.events.SecurityErrorEventTest);
		add(openfl.MemoryTest);
		add(openfl.LibTest);
		add(openfl.errors.ErrorTest);
		add(openfl.errors.SecurityErrorTest);
		add(openfl.errors.RangeErrorTest);
		add(openfl.errors.TypeErrorTest);
		add(openfl.errors.EOFErrorTest);
		add(openfl.errors.ArgumentErrorTest);
		add(openfl.errors.IllegalOperationErrorTest);
		add(openfl.system.ApplicationDomainTest);
		add(openfl.system.SecurityDomainTest);
		add(openfl.system.LoaderContextTest);
		add(openfl.system.CapabilitiesTest);
		add(openfl.system.SystemTest);
		add(openfl.display.DisplayObjectContainerTest);
		add(openfl.display.StageScaleModeTest);
		add(openfl.display.GraphicsPathWindingTest);
		add(openfl.display.StageAlignTest);
		add(openfl.display.StageDisplayStateTest);
		add(openfl.display.GraphicsSolidFillTest);
		add(openfl.display.GraphicsPathCommandTest);
		add(openfl.display.StageTest);
		add(openfl.display.SpriteTest);
		add(openfl.display.GraphicsEndFillTest);
		add(openfl.display.GraphicsTest);
		add(openfl.display.GradientTypeTest);
		add(openfl.display.LineScaleModeTest);
		add(openfl.display.DisplayObjectTest);
		add(openfl.display.LoaderTest);
		add(openfl.display.GraphicsStrokeTest);
		add(openfl.display.DirectRendererTest);
		add(openfl.display.StageQualityTest);
		add(openfl.display.JointStyleTest);
		add(openfl.display.BitmapDataChannelTest);
		add(openfl.display.BitmapDataTest);
		add(openfl.display.LoaderInfoTest);
		add(openfl.display.FPSTest);
		add(openfl.display.TriangleCullingTest);
		add(openfl.display.SimpleButtonTest);
		add(openfl.display.GraphicsGradientFillTest);
		add(openfl.display.BitmapTest);
		add(openfl.display.InteractiveObjectTest);
		add(openfl.display.PixelSnappingTest);
		add(openfl.display.CapsStyleTest);
		add(openfl.display.GraphicsBitmapFillTest);
		add(openfl.display.BlendModeTest);
		add(openfl.display.GraphicsPathTest);
		add(openfl.display.InterpolationMethodTest);
		add(openfl.display.SpreadMethodTest);
		add(openfl.display.MovieClipTest);
		add(openfl.display.TilesheetTest);
		add(openfl.display.ShapeTest);
		add(openfl.display.OpenGLViewTest);
		add(openfl.media.ID3InfoTest);
		add(openfl.media.SoundTransformTest);
		add(openfl.media.SoundLoaderContextTest);
		add(openfl.media.SoundChannelTest);
		add(openfl.media.SoundTest);
		add(openfl.text.TextLineMetricsTest);
		add(openfl.text.TextFormatTest);
		add(openfl.text.FontStyleTest);
		add(openfl.text.TextFormatAlignTest);
		add(openfl.text.TextFieldTypeTest);
		add(openfl.text.GridFitTypeTest);
		add(openfl.text.FontTypeTest);
		add(openfl.text.AntiAliasTypeTest);
		add(openfl.text.TextFieldAutoSizeTest);
		add(openfl.text.TextFieldTest);
		add(openfl.text.FontTest);
		add(openfl.AssetsTest);
		add(openfl.ui.MultitouchTest);
		add(openfl.ui.MouseTest);
		add(openfl.ui.MultitouchInputModeTest);
		add(openfl.ui.KeyboardTest);
		add(openfl.geom.ColorTransformTest);
		add(openfl.geom.Vector3DTest);
		add(openfl.geom.MatrixTest);
		add(openfl.geom.Matrix3DTest);
		add(openfl.geom.RectangleTest);
		add(openfl.geom.TransformTest);
		add(openfl.geom.PointTest);
		add(openfl.utils.EndianTest);
		add(openfl.utils.UInt8ArrayTest);
		add(openfl.utils.Int32ArrayTest);
		add(openfl.utils.Int16ArrayTest);
		add(openfl.utils.Float32ArrayTest);
		add(openfl.utils.TimerTest);
		add(openfl.utils.ByteArrayTest);
		add(openfl.utils.ArrayBufferViewTest);
		add(openfl.utils.ArrayBufferTest);
		add(openfl.utils.CompressionAlgorithmTest);
		add(openfl.gl.GLUniformLocationTest);
		add(openfl.gl.GLActiveInfoTest);
		add(openfl.gl.GLTextureTest);
		add(openfl.gl.GLContextAttributesTest);
		add(openfl.gl.GLRenderbufferTest);
		add(openfl.gl.GLFramebufferTest);
		add(openfl.gl.GLBufferTest);
		add(openfl.gl.GLProgramTest);
		add(openfl.gl.GLShaderTest);
		add(openfl.gl.GLTest);
		add(openfl.gl.GLObjectTest);
		add(openfl.sensors.AccelerometerTest);
		add(openfl.net.URLRequestTest);
		add(openfl.net.URLLoaderTest);
		add(openfl.net.URLRequestHeaderTest);
		add(openfl.net.SharedObjectFlushStatusTest);
		add(openfl.net.URLRequestMethodTest);
		add(openfl.net.URLVariablesTest);
		add(openfl.net.URLLoaderDataFormatTest);
		add(openfl.net.SharedObjectTest);
		add(openfl.external.ExternalInterfaceTest);
	}
}
