import DisplayObjectContainer from "./DisplayObjectContainer";


declare namespace openfl.display {

export class Stage extends DisplayObjectContainer {

	constructor(window:any, color?:any);
	align:any;
	allowsFullScreen:any;
	allowsFullScreenInteractive:any;
	application:any;
	color:any;
	contentsScaleFactor:any;
	displayState:any;
	focus:any;
	frameRate:any;
	fullScreenHeight:any;
	fullScreenWidth:any;
	quality:any;
	scaleMode:any;
	showDefaultContextMenu:any;
	softKeyboardRect:any;
	stage3Ds:any;
	stageFocusRect:any;
	stageHeight:any;
	stageWidth:any;
	window:any;
	__cacheFocus:any;
	__clearBeforeRender:any;
	__color:any;
	__colorSplit:any;
	__colorString:any;
	__contentsScaleFactor:any;
	__deltaTime:any;
	__dirty:any;
	__displayMatrix:any;
	__displayState:any;
	__dragBounds:any;
	__dragObject:any;
	__dragOffsetX:any;
	__dragOffsetY:any;
	__focus:any;
	__fullscreen:any;
	__invalidated:any;
	__lastClickTime:any;
	__logicalWidth:any;
	__logicalHeight:any;
	__macKeyboard:any;
	__mouseDownLeft:any;
	__mouseDownMiddle:any;
	__mouseDownRight:any;
	__mouseOverTarget:any;
	__mouseX:any;
	__mouseY:any;
	__primaryTouch:any;
	__renderer:any;
	__rendering:any;
	__rollOutStack:any;
	__stack:any;
	__touchData:any;
	__transparent:any;
	__wasDirty:any;
	__wasFullscreen:any;
	addRenderer(renderer:any):any;
	addWindow(window:any):any;
	registerModule(application:any):any;
	removeRenderer(renderer:any):any;
	removeWindow(window:any):any;
	setPreloader(preloader:any):any;
	unregisterModule(application:any):any;
	invalidate():any;
	localToGlobal(pos:any):any;
	onGamepadAxisMove(gamepad:any, axis:any, value:any):any;
	onGamepadButtonDown(gamepad:any, button:any):any;
	onGamepadButtonUp(gamepad:any, button:any):any;
	onGamepadConnect(gamepad:any):any;
	onGamepadDisconnect(gamepad:any):any;
	onJoystickAxisMove(joystick:any, axis:any, value:any):any;
	onJoystickButtonDown(joystick:any, button:any):any;
	onJoystickButtonUp(joystick:any, button:any):any;
	onJoystickConnect(joystick:any):any;
	onJoystickDisconnect(joystick:any):any;
	onJoystickHatMove(joystick:any, hat:any, position:any):any;
	onJoystickTrackballMove(joystick:any, trackball:any, value:any):any;
	onKeyDown(window:any, keyCode:any, modifier:any):any;
	onKeyUp(window:any, keyCode:any, modifier:any):any;
	onModuleExit(code:any):any;
	onMouseDown(window:any, x:any, y:any, button:any):any;
	onMouseMove(window:any, x:any, y:any):any;
	onMouseMoveRelative(window:any, x:any, y:any):any;
	onMouseUp(window:any, x:any, y:any, button:any):any;
	onMouseWheel(window:any, deltaX:any, deltaY:any):any;
	onPreloadComplete():any;
	onPreloadProgress(loaded:any, total:any):any;
	onRenderContextLost(renderer:any):any;
	onRenderContextRestored(renderer:any, context:any):any;
	onTextEdit(window:any, text:any, start:any, length:any):any;
	onTextInput(window:any, text:any):any;
	onTouchMove(touch:any):any;
	onTouchEnd(touch:any):any;
	onTouchStart(touch:any):any;
	onWindowActivate(window:any):any;
	onWindowClose(window:any):any;
	onWindowCreate(window:any):any;
	onWindowDeactivate(window:any):any;
	onWindowDropFile(window:any, file:any):any;
	onWindowEnter(window:any):any;
	onWindowFocusIn(window:any):any;
	onWindowFocusOut(window:any):any;
	onWindowFullscreen(window:any):any;
	onWindowLeave(window:any):any;
	onWindowMinimize(window:any):any;
	onWindowMove(window:any, x:any, y:any):any;
	onWindowResize(window:any, width:any, height:any):any;
	onWindowRestore(window:any):any;
	render(renderer:any):any;
	update(deltaTime:any):any;
	__broadcastEvent(event:any):any;
	__createRenderer():any;
	__drag(mouse:any):any;
	__getInteractive(stack:any):any;
	__globalToLocal(global:any, local:any):any;
	__handleError(e:any):any;
	__onKey(type:any, keyCode:any, modifier:any):any;
	__onGamepadConnect(gamepad:any):any;
	__onMouse(type:any, x:any, y:any, button:any):any;
	__onMouseWheel(deltaX:any, deltaY:any):any;
	__onTouch(type:any, touch:any):any;
	__resize():any;
	__setLogicalSize(width:any, height:any):any;
	__startDrag(sprite:any, lockCenter:any, bounds:any):any;
	__stopDrag(sprite:any):any;
	__update(transformOnly:any, updateChildren:any, maskGraphics?:any):any;
	get_color():any;
	set_color(value:any):any;
	get_contentsScaleFactor():any;
	get_displayState():any;
	set_displayState(value:any):any;
	get_focus():any;
	set_focus(value:any):any;
	get_frameRate():any;
	set_frameRate(value:any):any;
	get_fullScreenHeight():any;
	get_fullScreenWidth():any;
	set_height(value:any):any;
	get_mouseX():any;
	get_mouseY():any;
	set_rotation(value:any):any;
	set_scaleX(value:any):any;
	set_scaleY(value:any):any;
	set_transform(value:any):any;
	set_width(value:any):any;
	set_x(value:any):any;
	set_y(value:any):any;


}

}

export default openfl.display.Stage;