// import openfl.AssetsTest;
import openfl.desktop.ClipboardFormatsTest;
import openfl.desktop.ClipboardTest;
import openfl.desktop.ClipboardTransferModeTest;
import openfl.display.BitmapDataChannelTest;
import openfl.display.BitmapDataTest;
import openfl.display.BitmapTest;
import openfl.display.BlendModeTest;
import openfl.display.CapsStyleTest;
import openfl.display.DisplayObjectContainerTest;
import openfl.display.DisplayObjectTest;
import openfl.display.DOMElementTest;
import openfl.display.FPSTest;
import openfl.display.FrameLabelTest;
import openfl.display.GradientTypeTest;
import openfl.display.GraphicsBitmapFillTest;
import openfl.display.GraphicsEndFillTest;
import openfl.display.GraphicsGradientFillTest;
import openfl.display.GraphicsPathCommandTest;
import openfl.display.GraphicsPathTest;
import openfl.display.GraphicsPathWindingTest;
import openfl.display.GraphicsSolidFillTest;
import openfl.display.GraphicsStrokeTest;
import openfl.display.GraphicsTest;
import openfl.display.InteractiveObjectTest;
import openfl.display.InterpolationMethodTest;
import openfl.display.JointStyleTest;
import openfl.display.JPEGEncoderOptionsTest;
import openfl.display.LineScaleModeTest;
import openfl.display.LoaderInfoTest;
import openfl.display.LoaderTest;
import openfl.display.MovieClipTest;
import openfl.display.PixelSnappingTest;
import openfl.display.PNGEncoderOptionsTest;
import openfl.display.PreloaderTest;
import openfl.display.ShaderDataTest;
import openfl.display.ShaderInputTest;
import openfl.display.ShaderJobTest;
import openfl.display.ShaderParameterTest;
import openfl.display.ShaderParameterTypeTest;
import openfl.display.ShaderPrecisionTest;
import openfl.display.ShaderTest;
import openfl.display.ShapeTest;
import openfl.display.SimpleButtonTest;
import openfl.display.SpreadMethodTest;
import openfl.display.SpriteTest;
import openfl.display.Stage3DTest;
import openfl.display.StageAlignTest;
import openfl.display.StageDisplayStateTest;
import openfl.display.StageQualityTest;
import openfl.display.StageScaleModeTest;
import openfl.display.StageTest;
import openfl.display.TilemapTest;
import openfl.display.TilesetTest;
import openfl.display.TileTest;
import openfl.display.TriangleCullingTest;
import openfl.display3D.Context3DBlendFactorTest;
import openfl.display3D.Context3DBufferUsageTest;
import openfl.display3D.Context3DClearMaskTest;
import openfl.display3D.Context3DCompareModeTest;
import openfl.display3D.Context3DMipFilterTest;
import openfl.display3D.Context3DProfileTest;
import openfl.display3D.Context3DProgramTypeTest;
import openfl.display3D.Context3DRenderModeTest;
import openfl.display3D.Context3DStencilActionTest;
import openfl.display3D.Context3DTest;
import openfl.display3D.Context3DTextureFilterTest;
import openfl.display3D.Context3DTextureFormatTest;
import openfl.display3D.Context3DTriangleFaceTest;
import openfl.display3D.Context3DVertexBufferFormatTest;
import openfl.display3D.Context3DWrapModeTest;
import openfl.display3D.IndexBuffer3DTest;
import openfl.display3D.Program3DTest;
import openfl.display3D.textures.CubeTextureTest;
import openfl.display3D.textures.RectangleTextureTest;
import openfl.display3D.textures.TextureBaseTest;
import openfl.display3D.textures.TextureTest;
import openfl.display3D.VertexBuffer3DTest;
import openfl.errors.ArgumentErrorTest;
import openfl.errors.EOFErrorTest;
import openfl.errors.ErrorTest;
import openfl.errors.IllegalOperationErrorTest;
import openfl.errors.IOErrorTest;
import openfl.errors.RangeErrorTest;
import openfl.errors.SecurityErrorTest;
import openfl.errors.TypeErrorTest;
import openfl.events.AccelerometerEventTest;
import openfl.events.ActivityEventTest;
import openfl.events.AsyncErrorEventTest;
import openfl.events.DataEventTest;
import openfl.events.ErrorEventTest;
import openfl.events.EventDispatcherTest;
import openfl.events.EventPhaseTest;
import openfl.events.EventTest;
import openfl.events.FocusEventTest;
import openfl.events.FullScreenEventTest;
import openfl.events.GameInputEventTest;
import openfl.events.HTTPStatusEventTest;
import openfl.events.IOErrorEventTest;
import openfl.events.KeyboardEventTest;
import openfl.events.MouseEventTest;
import openfl.events.NetStatusEventTest;
import openfl.events.ProgressEventTest;
import openfl.events.SampleDataEventTest;
import openfl.events.SecurityErrorEventTest;
import openfl.events.TextEventTest;
import openfl.events.TimerEventTest;
import openfl.events.TouchEventTest;
import openfl.events.UncaughtErrorEventsTest;
import openfl.events.UncaughtErrorEventTest;
import openfl.external.ExternalInterfaceTest;
import openfl.filters.BitmapFilterTest;
import openfl.filters.BitmapFilterTypeTest;
import openfl.filters.BlurFilterTest;
import openfl.filters.ColorMatrixFilterTest;
import openfl.filters.DropShadowFilterTest;
import openfl.filters.GlowFilterTest;
import openfl.filters.ShaderFilterTest;
import openfl.geom.ColorTransformTest;
// import openfl.geom.Matrix3DTest;
import openfl.geom.MatrixTest;
import openfl.geom.Orientation3DTest;
import openfl.geom.PerspectiveProjectionTest;
import openfl.geom.PointTest;
import openfl.geom.RectangleTest;
import openfl.geom.TransformTest;
import openfl.geom.Utils3DTest;
import openfl.geom.Vector3DTest;
import openfl.LibTest;
import openfl.media.ID3InfoTest;
import openfl.media.SoundChannelTest;
import openfl.media.SoundLoaderContextTest;
import openfl.media.SoundTest;
import openfl.media.SoundTransformTest;
import openfl.MemoryTest;
import openfl.net.SharedObjectFlushStatusTest;
import openfl.net.SharedObjectTest;
import openfl.net.URLLoaderDataFormatTest;
import openfl.net.URLLoaderTest;
import openfl.net.URLRequestHeaderTest;
import openfl.net.URLRequestMethodTest;
import openfl.net.URLRequestTest;
import openfl.net.URLVariablesTest;
import openfl.sensors.AccelerometerTest;
import openfl.system.ApplicationDomainTest;
import openfl.system.CapabilitiesTest;
import openfl.system.LoaderContextTest;
import openfl.system.SecurityDomainTest;
import openfl.system.SystemTest;
import openfl.text.AntiAliasTypeTest;
import openfl.text.FontStyleTest;
import openfl.text.FontTest;
import openfl.text.FontTypeTest;
import openfl.text.GridFitTypeTest;
import openfl.text.TextFieldAutoSizeTest;
import openfl.text.TextFieldTest;
import openfl.text.TextFieldTypeTest;
import openfl.text.TextFormatAlignTest;
import openfl.text.TextFormatTest;
import openfl.text.TextLineMetricsTest;
import openfl.ui.KeyboardTest;
import openfl.ui.MouseTest;
import openfl.ui.MultitouchInputModeTest;
import openfl.ui.MultitouchTest;
import openfl.utils.ByteArrayTest;
import openfl.utils.CompressionAlgorithmTest;
import openfl.utils.DictionaryTest;
import openfl.utils.EndianTest;
import openfl.utils.TimerTest;
import openfl.VectorTest;

//

import openfl.display.Stage;
import openfl.display.Stage3D;


class Main {
	
	
	public static function main () {
		
		Mocha.before (function () {
			
			var stage = new Stage (550, 400);
			
		});
		
	}
	
	
}