import InteractiveObject from "./../display/InteractiveObject";

declare namespace openfl.text {

export class TextField extends InteractiveObject {

	constructor();
	antiAliasType:any;
	autoSize:any;
	background:any;
	backgroundColor:any;
	border:any;
	borderColor:any;
	bottomScrollV:any;
	caretIndex:any;
	defaultTextFormat:any;
	displayAsPassword:any;
	embedFonts:any;
	gridFitType:any;
	htmlText:any;
	length:any;
	maxChars:any;
	maxScrollH:any;
	maxScrollV:any;
	mouseWheelEnabled:any;
	multiline:any;
	numLines:any;
	restrict:any;
	scrollH:any;
	scrollV:any;
	selectable:any;
	selectionBeginIndex:any;
	selectionEndIndex:any;
	shader:any;
	sharpness:any;
	text:any;
	textColor:any;
	textHeight:any;
	textWidth:any;
	type:any;
	wordWrap:any;
	__bounds:any;
	__caretIndex:any;
	__cursorTimer:any;
	__dirty:any;
	__displayAsPassword:any;
	__inputEnabled:any;
	__isHTML:any;
	__layoutDirty:any;
	__mouseWheelEnabled:any;
	__offsetX:any;
	__offsetY:any;
	__selectionIndex:any;
	__showCursor:any;
	__symbol:any;
	__text:any;
	__htmlText:any;
	__textEngine:any;
	__textFormat:any;
	__div:any;
	appendText(text:any):any;
	getCharBoundaries(charIndex:any):any;
	getCharIndexAtPoint(x:any, y:any):any;
	getFirstCharInParagraph(charIndex:any):any;
	getLineIndexAtPoint(x:any, y:any):any;
	getLineIndexOfChar(charIndex:any):any;
	getLineLength(lineIndex:any):any;
	getLineMetrics(lineIndex:any):any;
	getLineOffset(lineIndex:any):any;
	getLineText(lineIndex:any):any;
	getParagraphLength(charIndex:any):any;
	getTextFormat(beginIndex?:any, endIndex?:any):any;
	replaceSelectedText(value:any):any;
	replaceText(beginIndex:any, endIndex:any, newText:any):any;
	setSelection(beginIndex:any, endIndex:any):any;
	setTextFormat(format:any, beginIndex?:any, endIndex?:any):any;
	__allowMouseFocus():any;
	__caretBeginningOfLine():any;
	__caretEndOfLine():any;
	__caretNextCharacter():any;
	__caretNextLine(lineIndex?:any, caretIndex?:any):any;
	__caretPreviousCharacter():any;
	__caretPreviousLine(lineIndex?:any, caretIndex?:any):any;
	__disableInput():any;
	__dispatch(event:any):any;
	__enableInput():any;
	__fromSymbol(swf:any, symbol:any):any;
	__getAdvance(position:any):any;
	__getBounds(rect:any, matrix:any):any;
	__getCharIndexOnDifferentLine(charIndex:any, lineIndex:any):any;
	__getCursor():any;
	__getGroup(x:any, y:any, precise?:any):any;
	__getPosition(x:any, y:any):any;
	__hitTest(x:any, y:any, shapeFlag:any, stack:any, interactiveOnly:any, hitObject:any):any;
	__hitTestMask(x:any, y:any):any;
	__renderCairo(renderSession:any):any;
	__renderCanvas(renderSession:any):any;
	__renderDOM(renderSession:any):any;
	__renderDOMClear(renderSession:any):any;
	__renderGL(renderSession:any):any;
	__renderGLMask(renderSession:any):any;
	__startCursorTimer():any;
	__startTextInput():any;
	__stopCursorTimer():any;
	__stopTextInput():any;
	__updateLayout():any;
	__updateScrollH():any;
	__updateText(value:any):any;
	__updateTransforms(overrideTransform?:any):any;
	get_antiAliasType():any;
	set_antiAliasType(value:any):any;
	get_autoSize():any;
	set_autoSize(value:any):any;
	get_background():any;
	set_background(value:any):any;
	get_backgroundColor():any;
	set_backgroundColor(value:any):any;
	get_border():any;
	set_border(value:any):any;
	get_borderColor():any;
	set_borderColor(value:any):any;
	get_bottomScrollV():any;
	get_cacheAsBitmap():any;
	get_caretIndex():any;
	get_defaultTextFormat():any;
	set_defaultTextFormat(value:any):any;
	get_displayAsPassword():any;
	set_displayAsPassword(value:any):any;
	get_embedFonts():any;
	set_embedFonts(value:any):any;
	get_gridFitType():any;
	set_gridFitType(value:any):any;
	get_height():any;
	set_height(value:any):any;
	get_htmlText():any;
	set_htmlText(value:any):any;
	get_length():any;
	get_maxChars():any;
	set_maxChars(value:any):any;
	get_maxScrollH():any;
	get_maxScrollV():any;
	get_mouseWheelEnabled():any;
	set_mouseWheelEnabled(value:any):any;
	get_multiline():any;
	set_multiline(value:any):any;
	get_numLines():any;
	get_restrict():any;
	set_restrict(value:any):any;
	get_scrollH():any;
	set_scrollH(value:any):any;
	get_scrollV():any;
	set_scrollV(value:any):any;
	get_selectable():any;
	set_selectable(value:any):any;
	get_selectionBeginIndex():any;
	get_selectionEndIndex():any;
	get_sharpness():any;
	set_sharpness(value:any):any;
	get_tabEnabled():any;
	get_text():any;
	set_text(value:any):any;
	get_textColor():any;
	set_textColor(value:any):any;
	get_textWidth():any;
	get_textHeight():any;
	get_type():any;
	set_type(value:any):any;
	get_width():any;
	set_width(value:any):any;
	get_wordWrap():any;
	set_wordWrap(value:any):any;
	stage_onMouseMove(event:any):any;
	stage_onMouseUp(event:any):any;
	this_onAddedToStage(event:any):any;
	this_onFocusIn(event:any):any;
	this_onFocusOut(event:any):any;
	this_onKeyDown(event:any):any;
	this_onMouseDown(event:any):any;
	window_onKeyDown(key:any, modifier:any):any;
	window_onTextInput(value:any):any;
	static __defaultTextFormat:any;
	static __missingFontWarning:any;


}

}

export default openfl.text.TextField;